name: recs-demo
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - numpy
    - xgboost
    - scikit-learn
    - sagemaker
    - boto3
    - flask
    - requests
    - matplotlib
    - seaborn
